title: (R)egular (E)xpressions 
email: samuel.thecurvature01@gmail.com
logo: /assets/img/logo.png
description: Quann's page for HPC & projects.
github.is_user_page: false
show_downloads: false 
google_analytics: G-MYD0HN3DS2
theme: jekyll-theme-minimal
